/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

  public static void main(String[] args) {
    var users = "[.sql/] select * from users".fetch();
    for (var u : users) {
      System.out.println(u);
    }

    var test = "[.sql/] select * from table".fetch();
    for (var u : test) {
      System.out.println(u);
    }
  }
}
